from extractor.pipeline import _attach_statement_types


def test_apple_statement_semantics_ignore_indexes_and_comprehensive_income():
    page_records = [
        {"page_number": 30, "text": "Item 8. Financial Statements and Supplementary Data\nIndex to Consolidated Financial Statements\nConsolidated Statements of Operations ... 29\nConsolidated Balance Sheets ... 31\nConsolidated Statements of Cash Flows ... 33"},
        {"page_number": 31, "text": "Apple Inc.\nCONSOLIDATED STATEMENTS OF OPERATIONS\n(In millions)\nYears ended\n2025\n2024\n2023\nTotal net sales 416,161 391,035 383,285"},
        {"page_number": 32, "text": "Apple Inc.\nCONSOLIDATED STATEMENTS OF COMPREHENSIVE INCOME\n(In millions)\nYears ended\n2025\n2024\n2023\nTotal comprehensive income 113,611 98,016 96,652"},
        {"page_number": 33, "text": "Apple Inc.\nCONSOLIDATED BALANCE SHEETS\n(In millions)\n2025\n2024\nCash and cash equivalents 35,934 29,943\nTotal assets 359,241 364,980"},
        {"page_number": 34, "text": "Notes to Consolidated Financial Statements"},
        {"page_number": 35, "text": "Apple Inc.\nCONSOLIDATED STATEMENTS OF CASH FLOWS\n(In millions)\nYears ended\n2025\n2024\n2023\nCash generated by operating activities 111,482 118,254 110,543"},
        {"page_number": 56, "text": "PART IV\nItem 15. Exhibit and Financial Statement Schedules\nIndex to Consolidated Financial Statements\nConsolidated Statements of Operations ..."},
    ]
    table_records = [
        {"page_number": 30, "validated": True, "score": 1.0, "table_title": None},
        {"page_number": 31, "validated": True, "score": 1.0, "table_title": None},
        {"page_number": 32, "validated": True, "score": 1.0, "table_title": None},
        {"page_number": 33, "validated": True, "score": 1.0, "table_title": None},
        {"page_number": 35, "validated": True, "score": 1.0, "table_title": None},
        {"page_number": 56, "validated": True, "score": 1.0, "table_title": None},
    ]

    selected = _attach_statement_types(page_records, table_records)

    assert selected["income_statement"] == [31]
    assert selected["balance_sheet"] == [33]
    assert selected["cash_flow"] == [35]

    assigned = {
        t["page_number"]: t["statement_type"]
        for t in table_records
        if t.get("statement_type")
    }
    assert assigned[31] == "income_statement"
    assert assigned[33] == "balance_sheet"
    assert assigned[35] == "cash_flow"
    assert 30 not in assigned
    assert 32 not in assigned
    assert 56 not in assigned


def test_statement_cluster_is_order_agnostic():
    page_records = [
        {"page_number": 9, "text": "Company\nCONSOLIDATED BALANCE SHEETS\nYears ended 2025 2024"},
        {"page_number": 7, "text": "Company\nCONSOLIDATED STATEMENTS OF CASH FLOWS\nYears ended 2025 2024"},
        {"page_number": 5, "text": "Company\nCONSOLIDATED STATEMENTS OF OPERATIONS\nYears ended 2025 2024"},
    ]
    table_records = [
        {"page_number": 5, "validated": True, "score": 1.0, "table_title": None},
        {"page_number": 7, "validated": True, "score": 1.0, "table_title": None},
        {"page_number": 9, "validated": True, "score": 1.0, "table_title": None},
    ]

    selected = _attach_statement_types(page_records, table_records)

    assert selected["income_statement"] == [5]
    assert selected["cash_flow"] == [7]
    assert selected["balance_sheet"] == [9]
