from __future__ import annotations

import re
from typing import Any, Dict, List, Optional, Tuple

from extractor.financial_resolver import compute_ebitda, compute_enterprise_value, resolve_metric, resolve_raw_text

FACT_ALIASES: Dict[str, Tuple[str, ...]] = {
    "cash_and_equivalents": ("cash and cash equivalents", "cash equivalents", "cash balance", "cash and bank balances", "cash and balances with banks"),
    "revenue": ("revenue from operations", "total revenue", "revenue", "net sales", "sales", "turnover"),
    "ebitda": ("operating ebitda", "ebitda"),
    "adjusted_ebitda": ("adjusted ebitda",),
    "ebit": ("operating profit", "profit from operations", "operating income", "ebit"),
    "depreciation": ("depreciation and amortisation", "depreciation and amortization", "depreciation & amortisation", "depreciation & amortization", "depreciation"),
    "pat": ("profit attributable to owners", "profit for the year", "profit for the period", "profit after tax", "net profit", "net income"),
    "pbt": ("profit before income tax", "profit before taxes", "profit before tax", "pre-tax profit"),
    "finance_costs": ("finance costs", "finance cost", "interest expense", "interest costs"),
    "cfo": ("net cash generated from operating activities", "cash flow from operating activities", "cash generated from operating activities", "cash generated by operating activities"),
    "capex": ("payments for acquisition of property, plant and equipment", "additions to property, plant and equipment", "capital expenditure", "purchase of property, plant and equipment", "purchase of fixed assets"),
    "total_assets": ("total assets",),
    "total_equity": ("total shareholders' equity", "equity attributable to owners", "total equity", "shareholders' equity"),
    "total_debt": ("total debt", "total borrowings", "borrowings", "commercial paper", "term debt", "notes payable", "bank loans", "loans", "debentures", "senior notes"),
    "market_capitalization": ("market capitalization", "market capitalisation", "market cap"),
    "enterprise_value": ("enterprise value",),
    "total_expenses": ("total expenses", "total expense", "total expenditure", "total operating expenses", "total operating expenditure", "total costs"),
}

DEBT_COMPONENT_LABELS = (
    "commercial paper", "term debt", "borrowings", "notes payable", "bank loans",
    "loans", "debentures", "senior notes", "revolving credit", "credit facilities",
)
DEBT_FLOW_LABELS = ("proceeds", "issuance", "repayments", "repayment", "cash flow", "borrowings issued")
YEAR_RE = re.compile(r"(?:FY\s*)?(?:19|20)\d{2}(?:[-/–]\d{2})?", re.I)


def _norm(value: Any) -> str:
    return re.sub(r"\s+", " ", str(value or "").strip().lower())


def _number(value: Any) -> Optional[float]:
    text = str(value or "").strip()
    if not text:
        return None
    negative = "(" in text and ")" in text
    cleaned = re.sub(r"[^0-9.\-]", "", text.replace("−", "-"))
    if not cleaned or cleaned in {"-", "."}:
        return None
    try:
        number = float(cleaned)
    except ValueError:
        return None
    return -abs(number) if negative else number


def _year_token(text: Any) -> Optional[str]:
    match = YEAR_RE.search(str(text or ""))
    return match.group(0) if match else None


def _period_columns(rows: List[List[Any]]) -> Dict[int, str]:
    periods: Dict[int, str] = {}
    for row in rows[:8]:
        if not isinstance(row, list):
            continue
        for idx, cell in enumerate(row):
            token = _year_token(cell)
            if token and idx > 0:
                periods[idx] = token
        if len(periods) >= 2:
            break
    return periods


def _scope_from_table(table: Dict[str, Any]) -> str:
    text = _norm(" ".join(str(table.get(k) or "") for k in ("table_title", "scope", "statement_assignment")))
    if "consolidated" in text:
        return "consolidated"
    if "standalone" in text or "separate financial" in text or "parent only" in text:
        return "standalone"
    return "unknown"


def _scale_from_metadata(metadata: Dict[str, Any]) -> Optional[str]:
    unit = metadata.get("unit") or metadata.get("currency_unit") or metadata.get("unit_scale")
    return str(unit) if unit else None


def _metric_for_label(label: str) -> Optional[str]:
    normalized = _norm(label)
    candidates: List[Tuple[int, str]] = []
    for metric, aliases in FACT_ALIASES.items():
        for alias in aliases:
            a = _norm(alias)
            if normalized == a or re.search(rf"(?<!\w){re.escape(a)}(?!\w)", normalized):
                candidates.append((len(a), metric))
    return max(candidates, key=lambda item: item[0])[1] if candidates else None


def _is_debt_flow(label: str, statement: str) -> bool:
    lowered = _norm(label)
    return statement == "cash_flow" or any(token in lowered for token in DEBT_FLOW_LABELS)


def _table_facts(statement: str, table: Dict[str, Any], metadata: Dict[str, Any]) -> List[Dict[str, Any]]:
    rows = table.get("table") or []
    periods = _period_columns(rows)
    if not rows:
        return []
    scope = _scope_from_table(table)
    unit = _scale_from_metadata(metadata)
    context: Optional[str] = None
    facts: List[Dict[str, Any]] = []
    for row_index, row in enumerate(rows):
        if not isinstance(row, list) or not row:
            continue
        label = str(row[0] or "").strip()
        numeric: List[Tuple[int, float]] = []
        for column_index, cell in enumerate(row[1:], start=1):
            value = _number(cell)
            if value is not None:
                numeric.append((column_index, value))
        if not numeric:
            if label and len(label) < 100 and not _year_token(label):
                context = label
            continue
        metric = _metric_for_label(label) or "unclassified"
        for column_index, value in numeric:
            fact = {
                "fact_id": None,
                "metric": metric,
                "label": label,
                "value": value,
                "period": periods.get(column_index),
                "column_index": column_index,
                "page": table.get("page_number_human") or table.get("page_number"),
                "statement": statement,
                "table_title": table.get("table_title"),
                "source": table.get("source"),
                "validated": bool(table.get("validated")),
                "score": float(table.get("score", 0) or 0),
                "statement_confidence": float(table.get("statement_confidence", 0) or 0),
                "section_context": context,
                "scope": scope,
                "unit": unit,
                "row_index": row_index,
                "is_flow_candidate": _is_debt_flow(label, statement),
                "status": "reported",
            }
            fact["fact_key"] = _fact_key(fact)
            facts.append(fact)
    return facts


def _resolver_facts(metric: str, data: Dict[str, Any], metadata: Dict[str, Any]) -> List[Dict[str, Any]]:
    facts: List[Dict[str, Any]] = []
    candidates = resolve_metric(metric, data) or resolve_raw_text(metric, data)
    for candidate in candidates:
        for idx, value in enumerate(candidate.get("values") or []):
            periods = candidate.get("periods") or []
            fact = {
                "fact_id": None,
                "metric": metric,
                "label": candidate.get("matched_alias") or metric,
                "value": float(value),
                "period": periods[idx] if idx < len(periods) else None,
                "column_index": idx + 1,
                "page": candidate.get("page"),
                "statement": candidate.get("statement"),
                "table_title": candidate.get("table_title"),
                "source": candidate.get("source"),
                "validated": bool(candidate.get("validated")),
                "score": float(candidate.get("score", 0) or 0),
                "statement_confidence": 0.5,
                "section_context": None,
                "scope": "unknown",
                "unit": _scale_from_metadata(metadata),
                "row_index": None,
                "is_flow_candidate": False,
                "status": "reported",
            }
            fact["fact_key"] = _fact_key(fact)
            facts.append(fact)
    return facts


def _fact_key(fact: Dict[str, Any]) -> Tuple[Any, ...]:
    return (
        fact.get("metric"), _norm(fact.get("label")), fact.get("value"), fact.get("period"),
        fact.get("scope"), fact.get("page"), fact.get("statement"), fact.get("row_index"), fact.get("column_index"),
    )


def _same_fact(a: Dict[str, Any], b: Dict[str, Any]) -> bool:
    try:
        same_value = abs(float(a.get("value", 0)) - float(b.get("value", 0))) < 1e-9
    except (TypeError, ValueError):
        same_value = a.get("value") == b.get("value")
    scopes = {a.get("scope") or "unknown", b.get("scope") or "unknown"}
    same_scope = len(scopes) == 1 or "unknown" in scopes
    return (
        a.get("metric") == b.get("metric")
        and same_value
        and a.get("period") == b.get("period")
        and a.get("page") == b.get("page")
        and a.get("statement") == b.get("statement")
        and same_scope
    )


def build_fact_store(data: Dict[str, Any]) -> Dict[str, Any]:
    metadata = data.get("summary", {}).get("metadata", {}) or {}
    facts: List[Dict[str, Any]] = []
    for statement, bucket in (data.get("statement_tables") or {}).items():
        for table in bucket.get("tables", []):
            facts.extend(_table_facts(statement, table, metadata))

    for metric in (
        "revenue", "ebit", "pat", "pbt", "depreciation", "finance_costs", "cash_and_equivalents",
        "cfo", "capex", "total_assets", "total_equity", "market_capitalization",
    ):
        for candidate in _resolver_facts(metric, data, metadata):
            if not any(_same_fact(candidate, existing) for existing in facts):
                facts.append(candidate)

    derived = []
    for calculation in (compute_ebitda(data), compute_enterprise_value(data)):
        if calculation and calculation.get("status") == "derived":
            derived.append(calculation)

    unique: List[Dict[str, Any]] = []
    seen_keys = set()
    for fact in facts:
        key = _fact_key(fact)
        if key in seen_keys:
            continue
        seen_keys.add(key)
        fact["fact_id"] = f"f{len(unique)}"
        fact["fact_key"] = key
        unique.append(fact)

    for calculation in derived:
        unique.append({
            "fact_id": f"d{len(unique)}", "metric": calculation.get("metric"), "label": calculation.get("metric"),
            "value": calculation.get("answer"), "period": calculation.get("period"), "column_index": None,
            "page": None, "statement": None, "table_title": None, "source": "calculation_engine",
            "validated": True, "score": 1.0, "statement_confidence": 1.0, "section_context": None,
            "scope": "unknown", "unit": _scale_from_metadata(metadata), "row_index": None,
            "is_flow_candidate": False, "status": "derived", "formula": calculation.get("formula"),
            "inputs": calculation.get("inputs", []),
            "fact_key": ("derived", calculation.get("metric"), calculation.get("period"), calculation.get("answer")),
        })

    return {
        "schema_version": "3.2",
        "document": {
            "source_name": data.get("summary", {}).get("source_name"),
            "currency": metadata.get("currency"),
            "unit": metadata.get("unit") or metadata.get("currency_unit"),
            "scope": metadata.get("standalone_or_consolidated") or "unknown",
        },
        "fact_count": len(unique),
        "facts": unique,
    }


def total_debt_candidates(facts: List[Dict[str, Any]], period: Optional[str] = None, scope: Optional[str] = None) -> List[Dict[str, Any]]:
    result: List[Dict[str, Any]] = []
    for fact in facts:
        if fact.get("statement") != "balance_sheet" or fact.get("status") != "reported" or fact.get("is_flow_candidate"):
            continue
        if period and fact.get("period") != period:
            continue
        if scope and scope != "unknown" and fact.get("scope") not in {scope, "unknown"}:
            continue
        label = _norm(fact.get("label"))
        if "total liabilities" in label:
            continue
        if any(token in label for token in DEBT_COMPONENT_LABELS):
            result.append(fact)
    return result


def fact_text(fact: Dict[str, Any]) -> str:
    return " | ".join(
        str(x) for x in (
            fact.get("metric"), fact.get("label"), fact.get("value"), fact.get("period"),
            fact.get("statement"), fact.get("scope"), fact.get("table_title"), fact.get("section_context"),
        ) if x not in (None, "")
    )
