from __future__ import annotations

from typing import Any, Dict, Iterable, List, Optional

from extractor.financial_resolver import compute_ebitda, compute_enterprise_value, resolve_metric, resolve_raw_text

FACT_ALIASES = {
    "cash_and_equivalents": ["cash and cash equivalents", "cash equivalents", "cash balance"],
    "revenue": ["revenue from operations", "total revenue", "revenue", "net sales", "sales"],
    "ebitda": ["ebitda"],
    "ebit": ["ebit", "operating profit", "profit from operations", "operating income"],
    "pat": ["profit for the year", "profit for the period", "profit after tax", "net profit", "net income"],
    "pbt": ["profit before tax", "profit before income tax", "profit before taxes"],
    "cfo": ["cash generated by operating activities", "cash flow from operating activities"],
    "capex": ["payments for acquisition of property, plant and equipment", "capital expenditure", "purchase of property"],
    "total_assets": ["total assets"],
    "total_equity": ["total shareholders' equity", "total equity", "shareholders' equity"],
    "total_debt": ["total debt", "commercial paper", "term debt", "borrowings"],
}

DEBT_COMPONENT_LABELS = ("commercial paper", "term debt", "borrowings")
DEBT_FLOW_LABELS = ("proceeds", "issuance", "repayments", "repayment", "cash flow")


def _norm(value: Any) -> str:
    import re
    return re.sub(r"\s+", " ", str(value or "").strip().lower())


def _number(value: Any) -> Optional[float]:
    import re
    text = str(value or "").strip()
    if not text:
        return None
    negative = "(" in text and ")" in text
    cleaned = re.sub(r"[^0-9.\-]", "", text.replace("−", "-"))
    if not cleaned or cleaned in {"-", "."}:
        return None
    try:
        number = float(cleaned)
    except ValueError:
        return None
    return -abs(number) if negative else number


def _periods(rows: List[List[Any]]) -> List[str]:
    import re
    year_re = re.compile(r"(?:FY\s*)?20\d{2}(?:[-/–]\d{2})?", re.I)
    for row in rows[:8]:
        found = year_re.findall(" ".join(map(str, row)))
        if found:
            return found
    return []


def _metric_for_label(label: str) -> Optional[str]:
    normalized = _norm(label)
    for metric, aliases in FACT_ALIASES.items():
        for alias in aliases:
            if normalized == _norm(alias) or _norm(alias) in normalized:
                return metric
    return None


def _table_facts(statement: str, table: Dict[str, Any]) -> List[Dict[str, Any]]:
    rows = table.get("table") or []
    periods = _periods(rows)
    facts: List[Dict[str, Any]] = []
    context = None
    for row_index, row in enumerate(rows):
        if not isinstance(row, list) or not row:
            continue
        label = str(row[0] or "").strip()
        values = [_number(cell) for cell in row[1:]]
        numeric = [value for value in values if value is not None]
        if not numeric:
            if label and len(label) < 100:
                context = label
            continue
        metric = _metric_for_label(label)
        lowered = _norm(label)
        is_flow = statement == "cash_flow" or any(token in lowered for token in DEBT_FLOW_LABELS)
        for idx, value in enumerate(numeric):
            facts.append({
                "fact_id": None,
                "metric": metric or "unclassified",
                "label": label,
                "value": value,
                "period": periods[idx] if idx < len(periods) else None,
                "page": table.get("page_number_human") or table.get("page_number"),
                "statement": statement,
                "table_title": table.get("table_title"),
                "source": table.get("source"),
                "validated": bool(table.get("validated")),
                "score": float(table.get("score", 0) or 0),
                "section_context": context,
                "row_index": row_index,
                "is_flow_candidate": is_flow,
                "status": "reported",
            })
    return facts


def _resolver_facts(metric: str, data: Dict[str, Any]) -> List[Dict[str, Any]]:
    facts: List[Dict[str, Any]] = []
    candidates = resolve_metric(metric, data) or resolve_raw_text(metric, data)
    for candidate in candidates:
        for idx, value in enumerate(candidate.get("values") or []):
            periods = candidate.get("periods") or []
            facts.append({
                "fact_id": None,
                "metric": metric,
                "label": candidate.get("matched_alias") or metric,
                "value": float(value),
                "period": periods[idx] if idx < len(periods) else None,
                "page": candidate.get("page"),
                "statement": candidate.get("statement"),
                "table_title": candidate.get("table_title"),
                "source": candidate.get("source"),
                "validated": bool(candidate.get("validated")),
                "score": float(candidate.get("score", 0) or 0),
                "section_context": None,
                "row_index": None,
                "is_flow_candidate": False,
                "status": "reported",
            })
    return facts


def build_fact_store(data: Dict[str, Any]) -> Dict[str, Any]:
    facts: List[Dict[str, Any]] = []
    for statement, bucket in (data.get("statement_tables") or {}).items():
        for table in bucket.get("tables", []):
            facts.extend(_table_facts(statement, table))

    # Fill gaps for metrics not represented cleanly in structured tables.
    for metric in ("revenue", "ebit", "pat", "pbt", "cash_and_equivalents", "cfo", "capex", "total_assets", "total_equity"):
        facts.extend(_resolver_facts(metric, data))

    derived = []
    for calculation in (compute_ebitda(data), compute_enterprise_value(data)):
        if calculation and calculation.get("status") == "derived":
            derived.append(calculation)

    seen = set()
    unique: List[Dict[str, Any]] = []
    for fact in facts:
        key = (
            fact.get("metric"), _norm(fact.get("label")), fact.get("value"),
            fact.get("period"), fact.get("page"), fact.get("statement"),
        )
        if key in seen:
            continue
        seen.add(key)
        fact["fact_id"] = f"f{len(unique)}"
        unique.append(fact)

    for calculation in derived:
        unique.append({
            "fact_id": f"d{len(unique)}",
            "metric": calculation.get("metric"),
            "label": calculation.get("metric"),
            "value": calculation.get("answer"),
            "period": calculation.get("period"),
            "page": None,
            "statement": None,
            "table_title": None,
            "source": "calculation_engine",
            "validated": True,
            "score": 1.0,
            "section_context": None,
            "row_index": None,
            "is_flow_candidate": False,
            "status": "derived",
            "formula": calculation.get("formula"),
            "inputs": calculation.get("inputs", []),
        })

    metadata = data.get("summary", {}).get("metadata", {}) or {}
    return {
        "schema_version": "2.0",
        "document": {
            "source_name": data.get("summary", {}).get("source_name"),
            "currency": metadata.get("currency"),
            "unit": metadata.get("unit") or metadata.get("currency_unit"),
        },
        "fact_count": len(unique),
        "facts": unique,
    }


def total_debt_candidates(facts: List[Dict[str, Any]], period: Optional[str] = None) -> List[Dict[str, Any]]:
    result = []
    for fact in facts:
        if fact.get("statement") != "balance_sheet" or fact.get("status") != "reported":
            continue
        if fact.get("is_flow_candidate"):
            continue
        if period and fact.get("period") != period:
            continue
        label = _norm(fact.get("label"))
        if any(token in label for token in DEBT_COMPONENT_LABELS) and "total liabilities" not in label:
            result.append(fact)
    return result
